# Generated by Django 4.1.4 on 2023-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoruAuctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('autoru_region', models.CharField(max_length=500, verbose_name='Регион')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('bid', models.IntegerField(verbose_name='Ставка')),
                ('competitors', models.IntegerField(verbose_name='Количество конкурентов с этой ставкой')),
                ('dealer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дилер')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.client')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.model')),
            ],
            options={
                'verbose_name': 'Авто.ру История Аукциона',
                'verbose_name_plural': 'Авто.ру История Аукциона',
                'db_table': 'auction_autoru_auction_history',
            },
        ),
    ]
