# Generated by Django 4.1.4 on 2024-10-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_model_options_model_unique_mark_model'),
        ('auction', '0002_alter_autoruauctionhistory_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoruauctionhistory',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark'),
        ),
        migrations.AlterField(
            model_name='autoruauctionhistory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.model'),
        ),
    ]
