# Generated by Django 4.1.4 on 2024-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0002_converterextraprocessing_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditional',
            name='value',
            field=models.CharField(help_text='Для фильтрации по нескольким значениям пиши каждое между `` и разделяй запятыми. Например: `E (W/S213)`, `CLS (C257)`', max_length=5000, verbose_name='Значение'),
        ),
    ]
