# Generated by Django 4.1.4 on 2024-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0006_convertertask_onllline_import_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='export_to_onllline',
            field=models.BooleanField(default=False, verbose_name='Экспортировать на площадки'),
        ),
    ]
