# Generated by Django 4.1.4 on 2024-03-18 09:08

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0010_alter_convertertask_export_to_websites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertertask',
            name='export_to_websites',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('-----', '-----'), ('новый файл для Excel', 'csv2'), ('auto.ru (новый каталог)', 'autoru'), ('avito.ru', 'avito'), ('drom.ru', 'drom'), ('Yandex Market', 'yandexYml'), ('110km.ru', '110km'), ('am.ru', 'automobile'), ('auto.ru (ком. транспорт)', 'comautoru'), ('autonavigator.ru', 'navigator'), ('avto25.ru', 'avto25'), ('bibika.ru', 'bibika'), ('carcopy.ru', 'carcopy'), ('car.ru', 'car'), ('cars.ru', 'cars'), ('carsguru.ru', 'carsguru'), ('Club Russia', 'clubrussia'), ('dmir.ru', 'dmir'), ('irr.ru', 'irr2'), ('quto.ru', 'quto'), ('usedcars.ru', 'usedcars'), ('yandex.yml', 'yandexYml'), ('vk.com', 'vk'), ('файл для Excel', 'csv')], default=list, max_length=255, null=True), blank=True, null=True, size=None, verbose_name='Экспорт на площадки'),
        ),
    ]
