# Generated by Django 4.1.4 on 2024-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0013_convertertask_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='add_to_price',
            field=models.URLField(blank=True, help_text='Если нужно добавить объявления к прайсу после конвертера то укажи здесь ссылку на прайс сэтими объявлениями', null=True, verbose_name='Добавить к прайсу'),
        ),
    ]
