# Generated by Django 4.1.4 on 2024-02-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_modificationcode_table'),
        ('teleph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephcall',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client', to_field='teleph_id', verbose_name='id клиента'),
        ),
    ]
