# Generated by Django 4.1.4 on 2024-09-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleph', '0004_alter_telephcall_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephcall',
            old_name='target',
            new_name='num_to',
        ),
    ]
