# Generated by Django 4.1.4 on 2024-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleph', '0006_auto_20240925_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephcall',
            name='target',
            field=models.CharField(max_length=255, null=True, verbose_name='Целевой'),
        ),
    ]
