# Generated by Django 4.1.4 on 2024-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['username'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
