# Generated by Django 4.1.4 on 2024-03-26 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_client_options_remove_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=10, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес пользователя')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='charge_type',
            field=models.CharField(choices=[('звонки', 'Звонки'), ('комиссия процент', 'Комиссия Процент'), ('комиссия сумма', 'Комиссия Сумма')], default='звонки', max_length=255, verbose_name='Тип'),
        ),
    ]
