# Generated by Django 4.1.4 on 2024-03-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_alter_client_charge_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='username',
        ),
    ]
