# Generated by Django 4.1.4 on 2024-08-08 09:27

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(default='name', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, verbose_name='Slug')),
                ('manager', models.CharField(max_length=255, null=True, verbose_name='Менеджер')),
                ('active', models.BooleanField(default='1', verbose_name='Активен')),
                ('charge_type', models.CharField(choices=[('звонки', 'Звонки'), ('комиссия процент', 'Комиссия Процент'), ('комиссия сумма', 'Комиссия Сумма')], default='звонки', max_length=255, verbose_name='Тип')),
                ('commission_size', models.FloatField(blank=True, null=True, verbose_name='Размер комиссии')),
                ('teleph_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя в телефонии')),
                ('autoru_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id авто.ру')),
                ('autoru_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя на авто.ру')),
                ('avito_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id авито')),
                ('drom_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id drom')),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_accounts', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_accounts', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['name'],
            },
        ),
    ]
