# Generated by Django 4.1.4 on 2024-08-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['email'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='autoru_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='autoru_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='avito_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='commission_size',
        ),
        migrations.RemoveField(
            model_name='account',
            name='drom_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teleph_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='AccountClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
