# Generated by Django 4.1.4 on 2024-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='name', max_length=255, verbose_name='Имя'),
        ),
    ]
