# Generated by Django 4.1.4 on 2024-09-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_application_registration'),
        ('accounts', '0007_alter_accountclient_account_and_more'),
    ]

    operations = [
    ]
