# Generated by Django 4.1.4 on 2024-09-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20240926_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price_url', models.CharField(max_length=2000, verbose_name='Ссылка на прайс')),
                ('datetime_updated', models.DateTimeField(verbose_name='Время последнего обновления')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Город салона')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('telephone', models.CharField(default='', max_length=255, verbose_name='Телефон')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='accounts.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
