# Generated by Django 4.1.4 on 2024-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0003_alter_conditional_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditional',
            name='condition',
            field=models.CharField(choices=[('in', 'содержит'), ('not in', 'не содержит'), ('==', 'равно'), ('!=', 'не равно'), ('>', 'больше'), ('<', 'меньше'), ('starts_with', 'начинается с'), ('not_starts_with', 'не начинается с'), ('ends_with', 'заканчивается на'), ('not_ends_with', 'не заканчивается на')], default=('==', 'равно'), max_length=500, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='converterextraprocessing',
            name='new_value',
            field=models.CharField(blank=True, help_text='Если одно значение для всех то пиши его, если из другого столбца то пиши имя столбцав формате: %col:"имя_столбца"', max_length=5000, null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='converterfilter',
            name='condition',
            field=models.CharField(choices=[('in', 'содержит'), ('not in', 'не содержит'), ('==', 'равно'), ('!=', 'не равно'), ('>', 'больше'), ('<', 'меньше'), ('starts_with', 'начинается с'), ('not_starts_with', 'не начинается с'), ('ends_with', 'заканчивается на'), ('not_ends_with', 'не заканчивается на')], default=('==', 'равно'), max_length=500, verbose_name='Условие'),
        ),
    ]
