# Generated by Django 4.1.4 on 2024-03-14 13:55

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0004_alter_conditional_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='export_to_websites',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('autoru', 'autoru'), ('avito', 'avito'), ('drom', 'drom')], default=list, max_length=255, null=True, verbose_name='Экспорт на площадки'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='convertertask',
            name='import_to_onllline',
            field=models.BooleanField(default=False, verbose_name='Импортировать в базу'),
        ),
        migrations.AddField(
            model_name='convertertask',
            name='onllline_salon_to_import',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер салона onllline.ru'),
        ),
    ]
