# Generated by Django 4.1.4 on 2024-03-15 13:49

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0007_convertertask_export_to_onllline'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='onllline_import_multiply_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размножить сток'),
        ),
        migrations.AddField(
            model_name='convertertask',
            name='onllline_import_options',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('save_images', 'Сохранить названия фото'), ('save_services', 'Оставлять услуги'), ('ad_add_vin', 'Присваивать ВИН модели')], default=list, max_length=255, null=True), blank=True, null=True, size=None, verbose_name='Опции импорта'),
        ),
    ]
