# Generated by Django 4.1.4 on 2024-03-21 10:48

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0012_alter_convertertask_export_to_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='default', max_length=500, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convertertask',
            name='export_to_onllline',
            field=models.BooleanField(default=False, help_text='Если отмечено то после импорта выгрузит на площадки по списку из Экспорт на площадки', verbose_name='Экспортировать на площадки'),
        ),
        migrations.AlterField(
            model_name='convertertask',
            name='export_to_websites',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('-----', '-----'), ('autoru', 'auto.ru (новый каталог)'), ('avito', 'avito.ru'), ('drom', 'drom.ru'), ('yandexYml', 'Yandex Market'), ('110km', '110km.ru'), ('automobile', 'am.ru'), ('comautoru', 'auto.ru (ком. транспорт)'), ('navigator', 'autonavigator.ru'), ('avto25', 'avto25.ru'), ('bibika', 'bibika.ru'), ('carcopy', 'carcopy.ru'), ('car', 'car.ru'), ('cars', 'cars.ru'), ('carsguru', 'carsguru.ru'), ('clubrussia', 'Club Russia'), ('dmir', 'dmir.ru'), ('irr2', 'irr.ru'), ('quto', 'quto.ru'), ('usedcars', 'usedcars.ru'), ('yandexYml', 'yandex.yml'), ('vk', 'vk.com'), ('csv', 'файл для Excel')], default=list, max_length=255, null=True), blank=True, help_text='Для выбора нескольких удерживай Ctrl', null=True, size=None, verbose_name='Экспорт на площадки'),
        ),
        migrations.AlterField(
            model_name='convertertask',
            name='import_to_onllline',
            field=models.BooleanField(default=False, help_text='Если отмечено то после конвертера прайс будет импортирован в салон в базе onllline.ru', verbose_name='Импортировать в базу'),
        ),
        migrations.AlterField(
            model_name='convertertask',
            name='onllline_import_options',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('-----', '-----'), ('save_images', 'Сохранить названия фото'), ('save_services', 'Оставлять услуги'), ('ad_add_vin', 'Присваивать ВИН модели')], default=list, max_length=255, null=True), blank=True, help_text='Для выбора нескольких удерживай Ctrl', null=True, size=None, verbose_name='Опции импорта'),
        ),
    ]
