# Generated by Django 5.0.3 on 2024-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0014_convertertask_add_to_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertertask',
            name='add_to_price',
            field=models.URLField(blank=True, help_text='Если нужно добавить объявления к прайсу после конвертера то укажи здесь ссылку на прайс сэтими объявлениями. Прайс размещай на наш ftp, в папке converter/имя_клиента/add/имя_файла.xlsx', null=True, verbose_name='Добавить к прайсу'),
        ),
    ]
