# Generated by Django 4.1.4 on 2024-05-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0015_alter_convertertask_add_to_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converterextraprocessing',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='converterextraprocessing',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='converterextraprocessing',
            name='price_column_to_change',
        ),
        migrations.RemoveField(
            model_name='converterextraprocessing',
            name='source',
        ),
        migrations.CreateModel(
            name='ConverterExtraProcessingNewChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Сток', 'Сток'), ('Прайс', 'Прайс')], max_length=500, verbose_name='Источник')),
                ('price_column_to_change', models.CharField(max_length=500, verbose_name='Столбец прайса в котором менять')),
                ('new_value', models.CharField(blank=True, help_text='Если одно значение для всех то пиши его, если из другого столбца то пиши имя столбцав формате: %col:"имя_столбца"', max_length=5000, null=True, verbose_name='Новое значение')),
                ('change_type', models.CharField(choices=[('Полностью', 'Полностью'), ('Добавить в начало', 'Добавить в начало'), ('Добавить в конец', 'Добавить в конец')], default=('Полностью', 'Полностью'), max_length=255, verbose_name='Как заменять')),
                ('converter_extra_processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoconverter.converterextraprocessing', verbose_name='Обработка прайса')),
            ],
            options={
                'verbose_name': 'Обработка прайса новое значение',
                'verbose_name_plural': 'Обработка прайса новые значения',
                'db_table': 'autoconverter_converter_extra_processing_new_changes',
            },
        ),
    ]
