# Generated by Django 4.1.4 on 2024-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0016_remove_converterextraprocessing_change_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converterextraprocessingnewchanges',
            name='source',
        ),
        migrations.AddField(
            model_name='conditional',
            name='source',
            field=models.CharField(choices=[('Сток', 'Сток'), ('Прайс', 'Прайс')], default='Прайс', max_length=500, verbose_name='Источник'),
            preserve_default=False,
        ),
    ]
