# Generated by Django 4.1.4 on 2024-05-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0017_remove_converterextraprocessingnewchanges_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditional',
            name='converter_extra_processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoconverter.converterextraprocessing'),
        ),
    ]
