# Generated by Django 4.1.4 on 2024-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0018_alter_conditional_converter_extra_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='converterextraprocessing',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заметка'),
        ),
        migrations.AddField(
            model_name='converterfilter',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заметка'),
        ),
    ]
