# Generated by Django 4.1.4 on 2024-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0019_converterextraprocessing_note_converterfilter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterextraprocessing',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
    ]
