# Generated by Django 4.1.4 on 2024-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0021_alter_converterfilter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterextraprocessingnewchanges',
            name='new_value',
            field=models.TextField(blank=True, help_text='Если одно значение для всех то пиши его, если из другого столбца то пиши имя столбцав формате: %col:"имя_столбца"', max_length=5000, null=True, verbose_name='Новое значение'),
        ),
    ]
