# Generated by Django 4.1.4 on 2024-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0022_alter_converterextraprocessingnewchanges_new_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='converterextraprocessing',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='converterfilter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='converterextraprocessingnewchanges',
            name='new_value',
            field=models.TextField(blank=True, help_text='Если одно значение для всех то пиши его, если из другого столбца то пиши имя столбцав формате: %col:"имя_столбца"', max_length=10000, null=True, verbose_name='Новое значение'),
        ),
    ]
