# Generated by Django 4.1.4 on 2024-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0024_alter_convertertask_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='change_vin',
            field=models.BooleanField(default=False, verbose_name='Изменить VIN'),
        ),
    ]
