# Generated by Django 4.1.4 on 2024-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0025_convertertask_change_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='use_converter',
            field=models.BooleanField(default=True, help_text='Если в качестве стока используется наш прайс и конвертер не нужен для подставки фото, то выключи это. ', verbose_name='Использовать конвертер'),
        ),
        migrations.AlterField(
            model_name='convertertask',
            name='change_vin',
            field=models.BooleanField(default=False, help_text='Меняет последние 6 цифр VIN на случайные. Если в последних 6 цифрах есть буква то меняет цифры после последней буквы.', verbose_name='Изменить VIN'),
        ),
    ]
