# Generated by Django 4.1.4 on 2024-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoconverter', '0026_convertertask_use_converter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='fill_vin',
            field=models.BooleanField(default=False, help_text='Добавляет в начало VIN знаки X если длина VIN меньше 17. Например VIN: 607130 станет XXXXXXXXXXX607130', verbose_name='Заполнить VIN знаками X'),
        ),
    ]
