# Generated by Django 4.1.4 on 2023-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoruRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoru_region_id', models.IntegerField(verbose_name='Авто.ру регион id')),
                ('name', models.CharField(max_length=500, verbose_name='Название региона')),
                ('path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Авто.ру Регион',
                'verbose_name_plural': 'Авто.ру Регионы',
                'db_table': 'autoru_autoru_region',
            },
        ),
        migrations.CreateModel(
            name='AutoruProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, null=True, verbose_name='id объявления')),
                ('vin', models.CharField(max_length=17, null=True, verbose_name='VIN')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('product', models.CharField(max_length=255, verbose_name='Услуга')),
                ('sum', models.FloatField(verbose_name='Стоимость')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('total', models.FloatField(verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.client', to_field='autoru_id', verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Авто.ру услуги',
                'verbose_name_plural': 'Авто.ру услуги',
                'db_table': 'autoru_autoru_product',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AutoruCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.IntegerField(blank=True, null=True, verbose_name='Марка id')),
                ('mark_name', models.CharField(max_length=500, verbose_name='Марка имя')),
                ('mark_code', models.CharField(max_length=500, verbose_name='Марка код')),
                ('folder_id', models.IntegerField(verbose_name='folder_id')),
                ('folder_name', models.CharField(max_length=500, verbose_name='folder_name')),
                ('model_id', models.IntegerField(blank=True, null=True, verbose_name='Модель id')),
                ('model_name', models.CharField(max_length=500, verbose_name='Модель имя')),
                ('model_code', models.CharField(max_length=500, verbose_name='Модель код')),
                ('generation_id', models.IntegerField(verbose_name='Поколение id')),
                ('generation_name', models.CharField(max_length=500, verbose_name='Поколение имя')),
                ('modification_id', models.IntegerField(verbose_name='Модификация id')),
                ('modification_name', models.CharField(max_length=500, verbose_name='Модификация имя')),
                ('configuration_id', models.IntegerField(verbose_name='configuration_id')),
                ('tech_param_id', models.IntegerField(verbose_name='tech_param_id')),
                ('body_type', models.CharField(max_length=500, verbose_name='Кузов')),
                ('years', models.CharField(max_length=500, verbose_name='Года выпуска')),
                ('complectation_id', models.IntegerField(blank=True, null=True, verbose_name='Комплектация id')),
                ('complectation_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комплектация имя')),
                ('my_mark_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark')),
                ('my_model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.model')),
            ],
            options={
                'verbose_name': 'Авто.ру Каталог',
                'verbose_name_plural': 'Авто.ру Каталог',
                'db_table': 'autoru_autoru_catalog',
            },
        ),
        migrations.CreateModel(
            name='AutoruCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, null=True, verbose_name='id объявления')),
                ('vin', models.CharField(max_length=17, null=True, verbose_name='VIN')),
                ('source', models.CharField(max_length=255, verbose_name='Исходящий')),
                ('target', models.CharField(max_length=255, verbose_name='Входящий')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('billing_state', models.CharField(max_length=255, null=True, verbose_name='Статус оплаты')),
                ('billing_cost', models.FloatField(null=True, verbose_name='Стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.client', to_field='autoru_id', verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Авто.ру звонки',
                'verbose_name_plural': 'Авто.ру звонки',
                'db_table': 'autoru_autoru_call',
                'ordering': ['datetime'],
            },
        ),
    ]
