# Generated by Django 4.1.4 on 2024-02-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_modificationcode_table'),
        ('autoru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoruproduct',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client', to_field='autoru_id', verbose_name='id клиента'),
        ),
    ]
