# Generated by Django 4.1.4 on 2024-05-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0003_autorugeneration_autorumark_autorumodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorumodel',
            old_name='id_folder_avtoru',
            new_name='id_folder_autoru',
        ),
    ]
