# Generated by Django 4.1.4 on 2024-09-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0004_autorucall_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorucall',
            old_name='source',
            new_name='num_from',
        ),
        migrations.RenameField(
            model_name='autorucall',
            old_name='target',
            new_name='num_to',
        ),
    ]
