# Generated by Django 4.1.4 on 2024-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0004_rename_id_folder_avtoru_autorumodel_id_folder_autoru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorugeneration',
            old_name='id_generation_avtoru',
            new_name='id_generation_autoru',
        ),
        migrations.RenameField(
            model_name='autorumodification',
            old_name='id_modification_avtoru',
            new_name='id_modification_autoru',
        ),
        migrations.AlterField(
            model_name='autorumodel',
            name='id_folder_autoru',
            field=models.IntegerField(verbose_name='Атрибут id у тега <folder> из xml файла. Значение ссылается на атрибут id тега <generation>'),
        ),
    ]
