# Generated by Django 4.1.4 on 2024-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0005_rename_source_autorucall_num_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoruproduct',
            name='total',
        ),
        migrations.AlterField(
            model_name='autoruproduct',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
