# Generated by Django 4.1.4 on 2024-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0005_rename_id_generation_avtoru_autorugeneration_id_generation_autoru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorumodel',
            name='id_folder_autoru',
            field=models.IntegerField(verbose_name='Поле id у тега <folder> из xml файла'),
        ),
    ]
