# Generated by Django 4.1.4 on 2024-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0006_remove_autoruproduct_total_alter_autoruproduct_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorucall',
            name='temp_client',
            field=models.IntegerField(blank=True, null=True, verbose_name='Временный id клиента'),
        ),
    ]
