# Generated by Django 4.1.4 on 2024-09-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0007_autorucall_temp_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorucall',
            name='client',
        ),
    ]
