# Generated by Django 4.1.4 on 2024-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0007_autorumark_id_mark_autoru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorumark',
            name='id_mark_autoru',
            field=models.IntegerField(blank=True, null=True, verbose_name='Атрибут id у тега <mark> из xml файла'),
        ),
    ]
