# Generated by Django 4.1.4 on 2024-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0008_alter_autorumark_id_mark_autoru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorucomplectation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название комплектации'),
        ),
    ]
