# Generated by Django 4.1.4 on 2024-09-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountclient_account_and_more'),
        ('autoru', '0008_remove_autorucall_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorucall',
            name='temp_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.client', verbose_name='id клиента'),
            preserve_default=False,
        ),
    ]
