# Generated by Django 4.1.4 on 2024-07-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0009_alter_autorucomplectation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorucatalog',
            name='my_mark_id',
        ),
        migrations.RemoveField(
            model_name='autorucatalog',
            name='my_model_id',
        ),
        migrations.AlterField(
            model_name='autorucomplectation',
            name='id_complectation_autoru',
            field=models.IntegerField(verbose_name='Идентификатор комплектации из XML-файла Авто.ру'),
        ),
        migrations.AlterField(
            model_name='autorucomplectation',
            name='modification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='autoru.autorumodification', verbose_name='Ссылка на соответствующую модификацию автомобиля.'),
        ),
        migrations.AlterField(
            model_name='autorugeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='autoru.autorumodel', verbose_name='Ссылка на соответствующую модель автомобиля.'),
        ),
        migrations.AlterField(
            model_name='autorumodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autoru.autorumark', verbose_name='Ссылка на соответствующую марку автомобиля.'),
        ),
        migrations.AlterField(
            model_name='autorumodification',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ёмкость батареи'),
        ),
    ]
