# Generated by Django 4.1.4 on 2024-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0009_alter_autorucall_temp_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorucall',
            old_name='temp_client',
            new_name='client',
        ),
    ]
