# Generated by Django 4.1.4 on 2024-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0010_rename_temp_client_autorucall_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoruproduct',
            name='temp_client',
            field=models.IntegerField(blank=True, null=True, verbose_name='Временный id клиента'),
        ),
    ]
