# Generated by Django 4.1.4 on 2024-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0011_remove_autorugeneration_id_generation_autoru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorumodification',
            name='power',
        ),
        migrations.AddField(
            model_name='autorumodification',
            name='power_hp',
            field=models.IntegerField(default=0, verbose_name='Мощность в лошадиных силах'),
        ),
        migrations.AddField(
            model_name='autorumodification',
            name='power_kw',
            field=models.IntegerField(default=0, verbose_name='Мощность в киловатах'),
        ),
    ]
