# Generated by Django 4.1.4 on 2024-09-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0011_autoruproduct_temp_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoruproduct',
            name='client',
        ),
    ]
