# Generated by Django 4.1.4 on 2024-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0012_remove_autorumodification_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorumark',
            name='id_mark_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение атрибута "name" у тега <mark> из xml-файла'),
        ),
    ]
