# Generated by Django 4.1.4 on 2024-09-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0013_alter_autoruproduct_temp_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoruproduct',
            old_name='temp_client',
            new_name='client',
        ),
    ]
