# Generated by Django 4.1.4 on 2024-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0006_remove_autoruproduct_total_alter_autoruproduct_vin'),
        ('autoru', '0013_alter_autorumark_id_mark_level'),
    ]

    operations = [
    ]
