# Generated by Django 4.1.4 on 2024-09-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_modification_power_modification_power_hp_and_more'),
        ('autoru', '0014_merge_20240926_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorucatalog',
            name='my_mark_id',
            field=models.ForeignKey(default=31844, on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autorucatalog',
            name='my_model_id',
            field=models.ForeignKey(default=304453, on_delete=django.db.models.deletion.PROTECT, to='mainapp.model'),
            preserve_default=False,
        ),
    ]
