# Generated by Django 4.1.4 on 2024-10-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoru', '0014_rename_temp_client_autoruproduct_client'),
        ('autoru', '0015_autorucatalog_my_mark_id_autorucatalog_my_model_id'),
    ]

    operations = [
    ]
