# Generated by Django 4.1.2 on 2022-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('manager', models.CharField(max_length=255, null=True, verbose_name='Менеджер')),
                ('active', models.BooleanField(default='1', verbose_name='Активен')),
                ('teleph_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя в телефонии')),
                ('autoru_id', models.IntegerField(null=True, unique=True, verbose_name='id авто.ру')),
                ('avito_id', models.IntegerField(null=True, unique=True, verbose_name='id авито')),
                ('drom_id', models.IntegerField(null=True, unique=True, verbose_name='id drom')),
            ],
        ),
    ]
