# Generated by Django 4.1.2 on 2022-10-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0002_marks_alter_clients_options_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('num_from', models.CharField(max_length=255, verbose_name='Исходящий')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('target', models.CharField(max_length=255, null=True, verbose_name='Входящий')),
                ('moderation', models.CharField(max_length=255, null=True, verbose_name='Модерация')),
                ('call_price', models.FloatField(verbose_name='Стоимость')),
                ('price_autoru', models.FloatField(verbose_name='Стоимость авто.ру')),
                ('price_drom', models.FloatField(verbose_name='Стоимость drom')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statsapp.clients', to_field='teleph_id', verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Телефония звонки',
                'verbose_name_plural': 'Телефония звонки',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='AutoruProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, null=True, verbose_name='id объявления')),
                ('vin', models.CharField(max_length=17, null=True, verbose_name='VIN')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('product', models.CharField(max_length=255, verbose_name='Услуга')),
                ('sum', models.FloatField(verbose_name='Стоимость')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('total', models.FloatField(verbose_name='Сумма')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statsapp.clients', to_field='autoru_id', verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Авто.ру услуги',
                'verbose_name_plural': 'Авто.ру услуги',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AutoruCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, null=True, verbose_name='id объявления')),
                ('vin', models.CharField(max_length=17, null=True, verbose_name='VIN')),
                ('source', models.CharField(max_length=255, verbose_name='Исходящий')),
                ('target', models.CharField(max_length=255, verbose_name='Входящий')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('mark', models.CharField(max_length=255, null=True, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('billing_state', models.CharField(max_length=255, null=True, verbose_name='Статус оплаты')),
                ('billing_cost', models.FloatField(verbose_name='Стоимость')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statsapp.clients', to_field='autoru_id', verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Авто.ру звонки',
                'verbose_name_plural': 'Авто.ру звонки',
                'ordering': ['datetime'],
            },
        ),
    ]
