# Generated by Django 4.1.2 on 2022-10-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0003_telephcalls_autoruproducts_autorucalls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='mark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statsapp.marks', to_field='mark', verbose_name='Марка'),
        ),
    ]
