# Generated by Django 4.1.2 on 2022-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0004_alter_models_mark_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorucalls',
            name='billing_cost',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='models',
            name='autoru',
            field=models.CharField(max_length=255, null=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='models',
            name='avito',
            field=models.CharField(max_length=255, null=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='models',
            name='drom',
            field=models.CharField(max_length=255, null=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='models',
            name='human_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Народное'),
        ),
        migrations.AlterField(
            model_name='models',
            name='teleph',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='telephcalls',
            name='call_price',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='telephcalls',
            name='price_autoru',
            field=models.FloatField(null=True, verbose_name='Стоимость авто.ру'),
        ),
        migrations.AlterField(
            model_name='telephcalls',
            name='price_drom',
            field=models.FloatField(null=True, verbose_name='Стоимость drom'),
        ),
    ]
