# Generated by Django 4.1.2 on 2022-10-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0005_alter_autorucalls_billing_cost_alter_models_autoru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorucalls',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='autoruproducts',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='telephcalls',
            old_name='client_id',
            new_name='client',
        ),
    ]
