# Generated by Django 4.1.2 on 2022-10-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0006_rename_client_id_autorucalls_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statsapp.marks', verbose_name='Марка'),
        ),
    ]
