# Generated by Django 4.1.2 on 2022-11-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0009_clients_charge_type_clients_commission_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='commission_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер комиссии'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='teleph_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя в телефонии'),
        ),
    ]
