# Generated by Django 4.1.4 on 2023-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0021_alter_stockfields_car_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConverterFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=500, verbose_name='Поле')),
                ('condition', models.CharField(choices=[('ends_with', 'заканчивается на'), ('contains', 'содержит'), ('not_ends_with', 'не заканчивается на'), ('not_contains', 'не содержит'), ('not_equals', 'не равно'), ('not_begins_with', 'не начинается с'), ('begins_with', 'начинается с'), ('equals', 'равно')], max_length=500, verbose_name='Условие')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('converter_task', models.ManyToManyField(to='statsapp.convertertask', verbose_name='Задача конвертера')),
            ],
            options={
                'verbose_name': 'Фильтр конвертера',
                'verbose_name_plural': 'Фильтры конвертера',
                'ordering': ['field'],
            },
        ),
    ]
