# Generated by Django 4.1.4 on 2023-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0043_autorucatalog_my_mark_id_autorucatalog_my_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='autoru_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя на авто.ру'),
        ),
    ]
