# Generated by Django 4.1.4 on 2023-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0048_autoruauctionhistory_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertertask',
            name='notifications_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Почта для уведомлений'),
        ),
    ]
