# Generated by Django 4.1.4 on 2023-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, verbose_name='Slug')),
                ('manager', models.CharField(max_length=255, null=True, verbose_name='Менеджер')),
                ('active', models.BooleanField(default='1', verbose_name='Активен')),
                ('charge_type', models.CharField(choices=[('звонки', 'звонки'), ('комиссия процент', 'комиссия процент'), ('комиссия сумма', 'комиссия сумма')], default='звонки', max_length=255, verbose_name='Тип')),
                ('commission_size', models.FloatField(blank=True, null=True, verbose_name='Размер комиссии')),
                ('teleph_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя в телефонии')),
                ('autoru_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id авто.ру')),
                ('autoru_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя на авто.ру')),
                ('avito_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id авито')),
                ('drom_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='id drom')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complectation', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=255, verbose_name='Поколение')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255, unique=True, verbose_name='Марка')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['mark'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=500, verbose_name='Расшифровка от клиента')),
                ('short_name', models.CharField(editable=False, max_length=255, verbose_name='Короткое название')),
                ('body_type', models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.', 'Внедорожник 3 дв.'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=100, verbose_name='Кузов')),
                ('engine_volume', models.IntegerField(blank=True, null=True, verbose_name='Объём двигателя')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('transmission', models.CharField(choices=[('автомат', 'автомат'), ('робот', 'робот'), ('вариатор', 'вариатор'), ('механика', 'механика')], max_length=100, verbose_name='Коробка передач')),
                ('engine_type', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('гибрид', 'гибрид'), ('электро', 'электро')], max_length=100, verbose_name='Тип двигателя')),
                ('drive', models.CharField(choices=[('передний', 'передний'), ('задний', 'задний'), ('полный', 'полный')], max_length=100, verbose_name='Привод')),
                ('battery_capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость батареи')),
                ('autoru_modification_id', models.IntegerField(blank=True, null=True, verbose_name='Авто.ру Модификация ID')),
                ('autoru_complectation_id', models.IntegerField(blank=True, null=True, verbose_name='Авто.ру Комплектация ID')),
                ('avito_modification_id', models.IntegerField(blank=True, null=True, verbose_name='Авито Модификация ID')),
                ('avito_complectation_id', models.IntegerField(blank=True, null=True, verbose_name='Авито Комплектация ID')),
                ('load_capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъёмность')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.CreateModel(
            name='ModificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500, verbose_name='Код')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.complectation', verbose_name='Комплектация')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.modification', verbose_name='Модификация')),
            ],
            options={
                'verbose_name': 'Код модификации',
                'verbose_name_plural': 'Коды модификации',
                'db_table': 'services_modification_codes',
            },
        ),
        migrations.AddField(
            model_name='modification',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modification_codes', to='services.modificationcode', verbose_name='Коды модификации'),
        ),
        migrations.AddField(
            model_name='modification',
            name='complectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifications', to='services.complectation', verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='modification',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.generation', verbose_name='Поколение'),
        ),
        migrations.AddField(
            model_name='modification',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='modification',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.model', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='generation',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.model', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='complectation',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complectations', to='services.modification', verbose_name='Модификация'),
        ),
    ]
