# Generated by Django 4.1.4 on 2023-11-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modificationcode',
            table='services_modification_code',
        ),
    ]
