# Generated by Django 4.1.4 on 2024-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('mark', 'model'), name='unique_mark_model'),
        ),
    ]
