# Generated by Django 4.1.4 on 2024-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_model_unique_mark_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='model',
            name='unique_mark_model',
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('mark', 'model'), name='old_unique_mark_model'),
        ),
    ]
