# Generated by Django 4.1.4 on 2024-04-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPrimatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кабинет Примател',
                'verbose_name_plural': 'Кабинеты Примател',
                'db_table': 'calls_cabinet',
            },
        ),
        migrations.CreateModel(
            name='ClientPrimatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный')),
                ('numbers', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номера')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Общая цена')),
                ('cabinet_primatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calls.cabinetprimatel', verbose_name='Кабинет Примател')),
                ('main_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Клиент Примател',
                'verbose_name_plural': 'Клиенты Примател',
                'db_table': 'calls_client_primatel',
            },
        ),
        migrations.CreateModel(
            name='SipPrimatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip_login', models.CharField(max_length=100, verbose_name='Sip логин')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.clientprimatel', verbose_name='Клиент Примател')),
            ],
            options={
                'verbose_name': 'Sip Примател',
                'verbose_name_plural': 'Sip Примател',
                'db_table': 'calls_sip_primatel',
            },
        ),
        migrations.CreateModel(
            name='ClientPrimatelMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.clientprimatel', verbose_name='Клиент Примател')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Клиент-Марка',
                'verbose_name_plural': 'Клиент-Марка',
                'db_table': 'calls_client_primatel_mark',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='id звонка')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('num_from', models.IntegerField(verbose_name='Исходящий')),
                ('num_to', models.IntegerField(verbose_name='Входящий')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('target', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('На модерацию', 'На модерацию'), ('ПМ - Целевой', 'ПМ - Целевой'), ('ПМ - Нецелевой', 'ПМ - Нецелевой')], max_length=100, null=True, verbose_name='Целевой')),
                ('other_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Остальные комментарии')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя менеджера')),
                ('moderation', models.CharField(blank=True, choices=[('М', 'М'), ('М(З)', 'М(З)'), ('М(Б)', 'М(Б)'), ('БУ', 'БУ'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Запас', 'Запас'), ('Доп. ресурсы', 'Доп. ресурсы')], max_length=100, null=True, verbose_name='М')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость автомобиля')),
                ('status', models.CharField(blank=True, choices=[('Обсуждают цену и авто', 'Обсуждают цену и авто'), ('Оставляет номер для перезвона', 'Оставляет номер для перезвона'), ('Никто не взял трубку', 'Никто не взял трубку'), ('Перевели, но Отдел продаж не взял трубку', 'Перевели, но Отдел продаж не взял трубку'), ('Повторный звонок', 'Повторный звонок'), ('Обратный звонок. Клиент не взял трубку', 'Обратный звонок. Клиент не взял трубку'), ('Клиент просит перезвонить', 'Клиент просит перезвонить'), ('КЦ не взял трубку', 'КЦ не взял трубку'), ('Звонок по БУ', 'Звонок по БУ'), ('Звонок по ТО', 'Звонок по ТО'), ('Запчасти', 'Запчасти'), ('Сорвался', 'Сорвался'), ('Не слышно клиента', 'Не слышно клиента'), ('Ошибочный звонок', 'Ошибочный звонок'), ('Другое', 'Другое')], max_length=100, null=True, verbose_name='Статус звонка')),
                ('call_price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость звонка')),
                ('manual_call_price', models.BooleanField(verbose_name='Ручное редактирование стоимости звонка')),
                ('color', models.CharField(blank=True, choices=[('бежевый', 'бежевый'), ('белый', 'белый'), ('бронзовый', 'бронзовый'), ('вишнёвый', 'вишнёвый'), ('голубой', 'голубой'), ('жёлтый', 'жёлтый'), ('зелёный', 'зелёный'), ('золотистый', 'золотистый'), ('индивидуальная окраска', 'индивидуальная окраска'), ('коричневый', 'коричневый'), ('красный', 'красный'), ('оранжевый', 'оранжевый'), ('пурпурный', 'пурпурный'), ('серебристый', 'серебристый'), ('серый', 'серый'), ('синий', 'синий'), ('фиолетовый', 'фиолетовый'), ('чёрный', 'чёрный')], max_length=100, null=True, verbose_name='Цвет')),
                ('body', models.CharField(blank=True, choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.Внедорожник 3 дв.', 'Jeep 3'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=100, null=True, verbose_name='Кузов')),
                ('drive', models.CharField(blank=True, choices=[('передний', 'передний'), ('задний', 'задний'), ('полный', 'полный')], max_length=100, null=True, verbose_name='Привод')),
                ('engine', models.CharField(blank=True, choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('гибрид', 'гибрид'), ('электро', 'электро')], max_length=100, null=True, verbose_name='Двигатель')),
                ('complectation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комплектация')),
                ('attention', models.BooleanField(default=False, verbose_name='Обратить внимание')),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='Город')),
                ('record', models.URLField(blank=True, null=True, verbose_name='Ссылка на запись звонка')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calls.clientprimatel', verbose_name='Клиент Примател')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.model', verbose_name='Модель')),
                ('sip_primatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calls.sipprimatel', verbose_name='Sip')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'db_table': 'calls_call',
            },
        ),
    ]
