# Generated by Django 4.1.4 on 2024-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_call_num_from_alter_call_num_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='manual_call_price',
            field=models.BooleanField(default=False, verbose_name='Ручное редактирование стоимости звонка'),
        ),
    ]
