# Generated by Django 4.1.4 on 2024-05-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_callpricesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callpricesetting',
            options={'verbose_name': 'Настройка стоимости звонка', 'verbose_name_plural': 'Настройки стоимости звонка'},
        ),
        migrations.AlterModelTable(
            name='callpricesetting',
            table='calls_call_price_setting',
        ),
    ]
