# Generated by Django 4.1.4 on 2024-05-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_model_unique_mark_model'),
        ('calls', '0007_remove_clientprimatel_main_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprimatel',
            name='price',
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='moderation',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('М(З)', 'М(З)'), ('М(Б)', 'М(Б)'), ('БУ', 'БУ'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Запас', 'Запас'), ('Доп. ресурсы', 'Доп. ресурсы')], max_length=255, null=True, verbose_name='Модерация'),
        ),
    ]
