# Generated by Django 4.1.4 on 2024-05-21 15:24

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_remove_clientprimatel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpricesetting',
            name='moderation',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('М', 'М'), ('М(З)', 'М(З)'), ('М(Б)', 'М(Б)'), ('БУ', 'БУ'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Запас', 'Запас'), ('Доп. ресурсы', 'Доп. ресурсы')], default=list, max_length=255, null=True), blank=True, null=True, size=None, verbose_name='Модерация'),
        ),
    ]
