# Generated by Django 4.1.4 on 2024-05-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_alter_callpricesetting_moderation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='price',
            new_name='car_price',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_id',
        ),
        migrations.AddField(
            model_name='call',
            name='calltouch_timestamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Timestamp в Calltouch'),
        ),
        migrations.AddField(
            model_name='call',
            name='primatel_call_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='id звонка Примател'),
        ),
        migrations.CreateModel(
            name='OurPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primatel', models.CharField(max_length=30, verbose_name='Номер Примател')),
                ('phone_calltouch', models.CharField(max_length=30, verbose_name='Номер Calltouch')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_phone_numbers', to='calls.clientprimatel', verbose_name='Клиент Примател')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
