# Generated by Django 4.1.4 on 2024-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_rename_price_call_car_price_remove_call_call_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourphonenumbers',
            options={'verbose_name': 'Наши номера', 'verbose_name_plural': 'Наши номера'},
        ),
        migrations.AlterModelTable(
            name='ourphonenumbers',
            table='calls_our_phone_numbers',
        ),
    ]
