# Generated by Django 4.1.4 on 2024-05-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_model_unique_mark_model'),
        ('calls', '0012_alter_ourphonenumbers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalltouchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('site_id', models.CharField(max_length=10, verbose_name='siteId')),
                ('token', models.CharField(max_length=500, verbose_name='token')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calltouch_settings', to='calls.clientprimatel', verbose_name='Клиент Примател')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Настройка Calltouch',
                'verbose_name_plural': 'Настройки Calltouch',
                'db_table': 'calls_calltouch_setting',
            },
        ),
    ]
