# Generated by Django 4.1.4 on 2024-05-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_calltouchsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurPhoneNumbers',
        ),
    ]
