# Generated by Django 4.1.4 on 2024-05-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_call_num_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalltouchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(verbose_name='timestamp')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('num_from', models.CharField(max_length=30, verbose_name='Исходящий')),
                ('num_to', models.CharField(max_length=30, verbose_name='Входящий')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('site_id', models.CharField(max_length=10, verbose_name='siteId')),
                ('site_name', models.CharField(max_length=100, verbose_name='Аккаунт Calltouch')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('successful', models.BooleanField(verbose_name='Успешный')),
                ('target', models.BooleanField(verbose_name='Целевой')),
                ('unique', models.BooleanField(verbose_name='Уникальный')),
                ('unique_target', models.BooleanField(verbose_name='Уникальный целевой')),
                ('our_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltouch_data', to='calls.call', verbose_name='Наш звонок')),
            ],
            options={
                'verbose_name': 'Данные Calltouch',
                'verbose_name_plural': 'Данные Calltouch',
                'db_table': 'calls_calltouch_data',
            },
        ),
    ]
