# Generated by Django 4.1.4 on 2024-05-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_calltouchdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='calltouch_timestamp',
        ),
        migrations.RemoveField(
            model_name='calltouchdata',
            name='our_call',
        ),
        migrations.AddField(
            model_name='call',
            name='calltouch_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.calltouchdata', verbose_name='Данные Calltouch'),
        ),
    ]
