# Generated by Django 4.1.4 on 2024-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_remove_call_calltouch_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltouchdata',
            name='call_tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='calltouchdata',
            name='calltouch_call_id',
            field=models.CharField(default='default', max_length=100, verbose_name='id звонка в Calltouch'),
            preserve_default=False,
        ),
    ]
