# Generated by Django 4.1.4 on 2024-07-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_calltouchdata_call_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField(verbose_name='Дата от')),
                ('dateto', models.DateField(verbose_name='Дата до')),
                ('plan', models.IntegerField(verbose_name='План')),
                ('plan_for_day', models.FloatField(verbose_name='План на день')),
                ('client_primatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.clientprimatel', verbose_name='Клиент Примател')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'db_table': 'calls_plan',
            },
        ),
    ]
