# Generated by Django 4.1.4 on 2024-07-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0019_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='repeat_call',
            field=models.BooleanField(default=False, verbose_name='Повторный звонок'),
            preserve_default=False,
        ),
    ]
