# Generated by Django 4.1.4 on 2024-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0021_alter_call_num_redirect_alter_call_sip_primatel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='manual_call_price',
        ),
        migrations.AddField(
            model_name='call',
            name='manual_edit',
            field=models.BooleanField(default=False, verbose_name='Ручное редактирование звонка'),
        ),
    ]
