# Generated by Django 4.1.4 on 2024-07-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0022_remove_call_manual_call_price_call_manual_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
    ]
