# Generated by Django 4.1.4 on 2024-08-01 13:16

from django.db import migrations, models
import libs.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0023_call_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='moderation',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('М(Б)', 'М(Б)'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Заявка А', 'Заявка А'), ('Заявка В', 'Заявка В'), ('Заявка С', 'Заявка С'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Доп. ресурсы', 'Доп. ресурсы')], max_length=100, null=True, verbose_name='М'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='moderation',
            field=libs.services.models.ChoiceArrayField(base_field=models.CharField(choices=[('М', 'М'), ('М(Б)', 'М(Б)'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Заявка А', 'Заявка А'), ('Заявка В', 'Заявка В'), ('Заявка С', 'Заявка С'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Доп. ресурсы', 'Доп. ресурсы')], default=list, max_length=255), size=None, verbose_name='Модерация'),
        ),
    ]
