# Generated by Django 4.1.4 on 2024-10-11 12:27

import applications.mainapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_model_options_model_unique_mark_model'),
        ('calls', '0027_alter_call_moderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='body',
            field=models.CharField(blank=True, choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.', 'Внедорожник 3 дв.'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=100, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='call',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='call',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='callpricesetting',
            name='moderation',
            field=applications.mainapp.models.ChoiceArrayField(base_field=models.CharField(choices=[('Авто.ру', 'Авто.ру'), ('Авто.ру (Б)', 'Авто.ру (Б)'), ('Авто.ру БУ', 'Авто.ру БУ'), ('Заявка', 'Заявка'), ('Заявка А', 'Заявка А'), ('Заявка В', 'Заявка В'), ('Заявка С', 'Заявка С'), ('Дром', 'Дром'), ('Авито', 'Авито'), ('Авито БУ', 'Авито БУ'), ('Доп. ресурсы', 'Доп. ресурсы')], default=list, max_length=255), size=None, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='calltouchsetting',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='clientprimatelmark',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mark', verbose_name='Марка'),
        ),
    ]
