# Generated by Django 4.1.4 on 2024-05-06 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название поколения')),
                ('id_generation_avito', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
                'db_table': 'avito_generations',
            },
        ),
        migrations.CreateModel(
            name='AvitoMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название марки')),
                ('id_mark_avito', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'db_table': 'avito_marks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvitoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название модели')),
                ('id_model_avito', models.IntegerField()),
                ('avito_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='avito.avitomark', verbose_name='Ссылка на марку')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'db_table': 'avito_models',
            },
        ),
        migrations.CreateModel(
            name='AvitoModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модификации')),
                ('years_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Годы от')),
                ('years_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год до')),
                ('clients_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Расшифровка от клиента')),
                ('short_name', models.CharField(editable=False, max_length=124, verbose_name='Короткое название')),
                ('drive', models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=64, verbose_name='Привод')),
                ('engine_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], max_length=64, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(choices=[('Автомат', 'Автомат'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор'), ('Механика', 'Механика')], max_length=64, verbose_name='Коробка передач')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('engine_volume', models.FloatField(blank=True, null=True, verbose_name='Объём двигателя')),
                ('body_type', models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.', 'Внедорожник 3 дв.'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=64, verbose_name='Кузов')),
                ('doors', models.IntegerField(blank=True, null=True, verbose_name='Количество дверей')),
                ('battery_capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость батареи')),
                ('load_capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъёмность')),
                ('id_modification_avito', models.IntegerField()),
                ('avito_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='avito.avitogeneration', verbose_name='Поколение к которой относится модификация')),
                ('avito_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito.avitomark', verbose_name='Марка к которой относится модификация')),
                ('avito_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito.avitomodel', verbose_name='Модель к которой относится модификация')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
                'db_table': 'avito_modifications',
            },
        ),
        migrations.AddField(
            model_name='avitogeneration',
            name='avito_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='avito.avitomodel', verbose_name='Ссылка на модель авто'),
        ),
        migrations.CreateModel(
            name='AvitoComplectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплектации')),
                ('id_complectation_avito', models.IntegerField()),
                ('avito_modification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='avito.avitomodification', verbose_name='Модификация')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'db_table': 'avito_complectations',
            },
        ),
    ]
