# Generated by Django 4.1.4 on 2024-05-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0002_avitomark_autoru_avitomark_avito_avitomark_drom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avitomark',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='avitomark',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='avitomark',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='avitomark',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='avitomark',
            name='teleph',
        ),
    ]
