# Generated by Django 4.1.4 on 2024-05-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_remove_avitomark_autoru_remove_avitomark_avito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitocomplectation',
            old_name='avito_modification',
            new_name='modification',
        ),
        migrations.RenameField(
            model_name='avitogeneration',
            old_name='avito_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='avitomodel',
            old_name='avito_mark',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='avitomodification',
            old_name='avito_generation',
            new_name='generation',
        ),
        migrations.RenameField(
            model_name='avitomodification',
            old_name='avito_mark',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='avitomodification',
            old_name='avito_model',
            new_name='model',
        ),
    ]
