# Generated by Django 4.1.4 on 2024-05-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0004_rename_avito_modification_avitocomplectation_modification_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avitocomplectation',
            table='avito_complectation',
        ),
        migrations.AlterModelTable(
            name='avitogeneration',
            table='avito_generation',
        ),
        migrations.AlterModelTable(
            name='avitomark',
            table='avito_mark',
        ),
        migrations.AlterModelTable(
            name='avitomodel',
            table='avito_model',
        ),
        migrations.AlterModelTable(
            name='avitomodification',
            table='avito_modification',
        ),
    ]
