# Generated by Django 4.1.4 on 2024-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0005_alter_avitocomplectation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitocomplectation',
            name='id_complectation_avito',
            field=models.IntegerField(verbose_name='id из xml файла авито'),
        ),
        migrations.AlterField(
            model_name='avitogeneration',
            name='id_generation_avito',
            field=models.IntegerField(verbose_name='id из xml файла авито'),
        ),
        migrations.AlterField(
            model_name='avitomark',
            name='id_mark_avito',
            field=models.IntegerField(verbose_name='id из xml файла авито'),
        ),
        migrations.AlterField(
            model_name='avitomodel',
            name='id_model_avito',
            field=models.IntegerField(verbose_name='id из xml файла авито'),
        ),
        migrations.AlterField(
            model_name='avitomodification',
            name='id_modification_avito',
            field=models.IntegerField(verbose_name='id из xml файла авито'),
        ),
    ]
