# Generated by Django 4.1.4 on 2024-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0006_alter_avitocomplectation_id_complectation_avito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitocomplectation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название комплектации'),
        ),
    ]
