# Generated by Django 4.1.4 on 2024-03-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoruParsedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('region', models.CharField(max_length=500, verbose_name='Регион')),
                ('complectation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комплектация')),
                ('modification', models.CharField(blank=True, max_length=500, null=True, verbose_name='Модификация')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('dealer', models.CharField(max_length=500, verbose_name='Имя дилера')),
                ('price_with_discount', models.IntegerField(verbose_name='Цена со скидками')),
                ('price_no_discount', models.IntegerField(verbose_name='Цена без скидок')),
                ('with_nds', models.BooleanField(verbose_name='Цена с НДС')),
                ('position_actual', models.IntegerField(verbose_name='Позиция по актуальности')),
                ('position_total', models.IntegerField(verbose_name='Позиция общая')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('condition', models.CharField(max_length=500, verbose_name='Состояние/пробег')),
                ('in_stock', models.CharField(max_length=500, verbose_name='Наличие')),
                ('services', models.CharField(blank=True, max_length=500, null=True, verbose_name='Услуги')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Стикеры')),
                ('photos', models.IntegerField(verbose_name='Количество фото')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.model')),
            ],
            options={
                'verbose_name': 'Спарсенное объявление авто.ру',
                'verbose_name_plural': 'Спарсенные объявления авто.ру',
                'db_table': 'srav_autoru_parsed_ad',
            },
        ),
    ]
