# Generated by Django 4.1.4 on 2023-12-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SravPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_price', models.IntegerField(verbose_name='Позиция по цене')),
                ('in_stock_count', models.IntegerField(verbose_name='В наличии')),
                ('for_order_count', models.IntegerField(verbose_name='Под заказ')),
                ('autoru_parsed_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srav.autoruparsedad')),
            ],
            options={
                'verbose_name': 'Сравнительная',
                'verbose_name_plural': 'Сравнительная',
                'db_table': 'srav_srav_pivot',
            },
        ),
    ]
