# Generated by Django 4.1.4 on 2023-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0002_sravpivot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sravpivot',
            name='price_no_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Разница цены без скидок'),
        ),
        migrations.AddField(
            model_name='sravpivot',
            name='price_with_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Разница цены со скидками'),
        ),
    ]
