# Generated by Django 4.1.4 on 2023-12-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0003_sravpivot_price_no_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sravpivot',
            old_name='price_no_discount',
            new_name='price_no_discount_diff',
        ),
        migrations.RenameField(
            model_name='sravpivot',
            old_name='price_with_discount',
            new_name='price_with_discount_diff',
        ),
    ]
