# Generated by Django 4.1.4 on 2023-12-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0004_rename_price_no_discount_sravpivot_price_no_discount_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sravpivot',
            name='price_no_discount_diff',
        ),
        migrations.RemoveField(
            model_name='sravpivot',
            name='price_with_discount_diff',
        ),
    ]
