# Generated by Django 4.1.4 on 2024-07-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_model_unique_mark_model'),
        ('srav', '0006_alter_autoruparsedad_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueAutoruParsedAdRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=500, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Уникальный Регион из спарсенных объявлений авто.ру',
                'verbose_name_plural': 'Уникальные Регионы из спарсенных объявлений авто.ру',
                'db_table': 'srav_unique_autoru_parsed_ad_region',
            },
        ),
        migrations.CreateModel(
            name='UniqueAutoruParsedAdMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Уникальная Марка из спарсенных объявлений авто.ру',
                'verbose_name_plural': 'Уникальные Марки из спарсенных объявлений авто.ру',
                'db_table': 'srav_unique_autoru_parsed_ad_mark',
            },
        ),
    ]
