# Generated by Django 4.1.4 on 2024-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0007_uniqueautoruparsedadregion_uniqueautoruparsedadmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueAutoruParsedAdDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.CharField(max_length=500, verbose_name='Имя дилера')),
            ],
            options={
                'verbose_name': 'Уникальный Дилер из спарсенных объявлений авто.ру',
                'verbose_name_plural': 'Уникальные Дилеры из спарсенных объявлений авто.ру',
                'db_table': 'srav_unique_autoru_parsed_ad_dealer',
            },
        ),
    ]
