# Generated by Django 4.1.4 on 2024-07-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srav', '0008_uniqueautoruparsedaddealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueautoruparsedaddealer',
            name='dealer',
            field=models.CharField(max_length=500, unique=True, verbose_name='Имя дилера'),
        ),
        migrations.AlterField(
            model_name='uniqueautoruparsedadregion',
            name='region',
            field=models.CharField(max_length=500, unique=True, verbose_name='Регион'),
        ),
    ]
