# Generated by Django 4.1.4 on 2024-07-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_model_unique_mark_model'),
        ('srav', '0009_alter_uniqueautoruparsedaddealer_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueautoruparsedadmark',
            name='mark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.mark', verbose_name='Марка'),
        ),
    ]
