# Generated by Django 4.1.4 on 2024-08-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account'),
        ('srav', '0010_alter_uniqueautoruparsedadmark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoruparsedad',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client'),
        ),
    ]
