# Generated by Django 4.1.4 on 2024-04-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Поколение')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Марка')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_from', models.IntegerField(verbose_name='Годы от')),
                ('years_to', models.IntegerField(verbose_name='Год до')),
                ('clients_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Расшифровка от клиента')),
                ('short_name', models.CharField(editable=False, max_length=255, verbose_name='Короткое название')),
                ('name', models.CharField(max_length=100, verbose_name='Название модификации')),
                ('drive', models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=100, verbose_name='Привод')),
                ('engine_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], max_length=100, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(choices=[('AT', 'Автомат'), ('AMT', 'Робот'), ('CVT', 'Вариатор'), ('MT', 'Механика')], max_length=100, verbose_name='Коробка передач')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('engine_volume', models.IntegerField(blank=True, null=True, verbose_name='Объём двигателя')),
                ('body_type', models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.', 'Внедорожник 3 дв.'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=100, verbose_name='Кузов')),
                ('doors', models.IntegerField(blank=True, null=True, verbose_name='Количество дверей')),
                ('battery_capacity', models.IntegerField(blank=True, null=True, verbose_name='Ёмкость батареи')),
                ('load_capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъёмность')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='mainapp.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mark', verbose_name='Марка к которой относится модификация')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.model', verbose_name='Модель к которой относится модификация')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='mainapp.model', verbose_name='Модель автомобиля'),
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплектации')),
                ('teleph', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефония')),
                ('autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авто.ру')),
                ('avito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авито')),
                ('drom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drom')),
                ('human_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Народное')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='mainapp.modification', verbose_name='Модификация')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
            },
        ),
    ]
