# Generated by Django 4.1.4 on 2024-05-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mark', verbose_name='Марка'),
        ),
    ]
