# Generated by Django 4.1.4 on 2024-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_model_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём двигателя'),
        ),
    ]
