# Generated by Django 4.1.4 on 2024-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_modification_engine_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'AT'), ('Робот', 'AMT'), ('Вариатор', 'CVT'), ('Механика', 'MT')], max_length=100, verbose_name='Коробка передач'),
        ),
    ]
