# Generated by Django 4.1.4 on 2024-05-03 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_modification_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectation',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='human_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Народное'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='human_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Народное'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='mainapp.model', verbose_name='Ссылка на модель авто'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название поколения'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='human_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Народное'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название марки'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='model',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='model',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='model',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='model',
            name='human_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Народное'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mainapp.mark', verbose_name='Ссылка на марку'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='model',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='body_type',
            field=models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.', 'Внедорожник 3 дв.'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=64, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='clients_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Расшифровка от клиента'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='drive',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=64, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='engine_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], max_length=64, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='mainapp.generation', verbose_name='Поколение к которой относится модификация'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='short_name',
            field=models.CharField(editable=False, max_length=124, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор'), ('Механика', 'Механика')], max_length=64, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='years_from',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Годы от'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='years_to',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год до'),
        ),
    ]
