# Generated by Django 4.1.4 on 2024-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_complectation_autoru_alter_complectation_avito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectation',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефония'),
        ),
        migrations.AlterField(
            model_name='model',
            name='autoru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авто.ру'),
        ),
        migrations.AlterField(
            model_name='model',
            name='avito',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Авито'),
        ),
        migrations.AlterField(
            model_name='model',
            name='drom',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Drom'),
        ),
        migrations.AlterField(
            model_name='model',
            name='teleph',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефония'),
        ),
    ]
