# Generated by Django 4.1.4 on 2024-05-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_modification_autoru_modification_avito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complectation',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='complectation',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='complectation',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='complectation',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='complectation',
            name='teleph',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='teleph',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teleph',
        ),
        migrations.RemoveField(
            model_name='model',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='model',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='model',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='model',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='teleph',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='autoru',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='avito',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='drom',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='human_name',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='teleph',
        ),
    ]
