# Generated by Django 4.1.4 on 2024-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_generation_autoru_generation_avito_generation_drom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название комплектации'),
        ),
    ]
