# Generated by Django 4.1.4 on 2024-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_modification_power_modification_power_hp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('mark', 'name'), name='unique_mark_model2'),
        ),
    ]
