# Generated by Django 4.1.4 on 2024-03-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price_url', models.CharField(max_length=2000, verbose_name='Ссылка на прайс')),
                ('datetime_updated', models.DateTimeField(verbose_name='Время последнего обновления')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Город салона')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('telephone', models.CharField(default='', max_length=255, verbose_name='Телефон')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complectation', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('body_type', models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.Внедорожник 3 дв.', 'Jeep 3'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=64, verbose_name='Кузов')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(choices=[('бежевый', 'бежевый'), ('белый', 'белый'), ('бронзовый', 'бронзовый'), ('вишнёвый', 'вишнёвый'), ('голубой', 'голубой'), ('жёлтый', 'жёлтый'), ('зелёный', 'зелёный'), ('золотистый', 'золотистый'), ('индивидуальная окраска', 'индивидуальная окраска'), ('коричневый', 'коричневый'), ('красный', 'красный'), ('оранжевый', 'оранжевый'), ('пурпурный', 'пурпурный'), ('серебристый', 'серебристый'), ('серый', 'серый'), ('синий', 'синий'), ('фиолетовый', 'фиолетовый'), ('чёрный', 'чёрный')], max_length=64, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('original_vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='Исходный VIN')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('photo', models.CharField(blank=True, max_length=10500, verbose_name='Ссылка на фото')),
                ('price_nds', models.CharField(blank=True, max_length=8, null=True, verbose_name='Цена c НДС')),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя')),
                ('power', models.IntegerField(blank=True, verbose_name='Мощность')),
                ('engine_type', models.CharField(blank=True, max_length=32, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(blank=True, max_length=16, verbose_name='Коробка передач')),
                ('drive', models.CharField(blank=True, max_length=32, verbose_name='Привод')),
                ('modification', models.CharField(blank=True, max_length=128, verbose_name='Модификация')),
                ('trade_in', models.IntegerField(blank=True, null=True, verbose_name='Трейд-ин')),
                ('credit', models.IntegerField(blank=True, null=True, verbose_name='Кредит')),
                ('insurance', models.IntegerField(blank=True, null=True, verbose_name='Страховка')),
                ('max_discount', models.IntegerField(blank=True, null=True, verbose_name='Максимальная скидка')),
                ('condition', models.CharField(blank=True, max_length=16, null=True, verbose_name='Состояние машины')),
                ('run', models.IntegerField(blank=True, default=0, null=True, verbose_name='Пробег')),
                ('modification_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код модификации')),
                ('color_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код цвета')),
                ('interior_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Код интерьера')),
                ('configuration_codes', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Коды опций комплектации')),
                ('stickers_autoru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Стикеры авто.ру')),
                ('video', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на видео')),
                ('telephone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона')),
                ('availability', models.CharField(blank=True, max_length=32, null=True, verbose_name='Наличие')),
                ('id_model_autoru', models.IntegerField(blank=True, null=True, verbose_name='ID модели на авто.ру')),
                ('id_modification_autoru', models.IntegerField(blank=True, null=True, verbose_name='ID модификации на авто.ру')),
                ('modification_autoru', models.CharField(blank=True, max_length=64, null=True, verbose_name='Модификация авто.ру')),
                ('configuration_autoru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комплектация авто.ру')),
                ('status', models.CharField(blank=True, max_length=16, null=True, verbose_name='Статус продажи')),
                ('id_client', models.CharField(blank=True, max_length=32, null=True, verbose_name='ID от клиента')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания и размещения')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='services.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='services.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'ads_ad',
            },
        ),
    ]
