# Generated by Django 4.1.4 on 2023-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_modification_body_type'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('body_type', models.CharField(choices=[('Внедорожник', 'Внедорожник'), ('Внедорожник 3 дв.Внедорожник 3 дв.', 'Jeep 3'), ('Внедорожник 5 дв.', 'Внедорожник 5 дв.'), ('Внедорожник Coupe', 'Внедорожник Coupe'), ('Внедорожник ESV', 'Внедорожник ESV'), ('Внедорожник Grand', 'Внедорожник Grand'), ('Внедорожник L', 'Внедорожник L'), ('Внедорожник Long', 'Внедорожник Long'), ('Внедорожник X', 'Внедорожник X'), ('Кабриолет', 'Кабриолет'), ('Компактвэн', 'Компактвэн'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Микроавтобус', 'Микроавтобус'), ('Минивэн', 'Минивэн'), ('Минивэн Long', 'Минивэн Long'), ('Пикап', 'Пикап'), ('Родстер', 'Родстер'), ('Седан', 'Седан'), ('Седан Long', 'Седан Long'), ('Седан Pullman', 'Седан Pullman'), ('Тарга', 'Тарга'), ('Универсал', 'Универсал'), ('Универсал Cross', 'Универсал Cross'), ('Хэтчбек', 'Хэтчбек'), ('Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'), ('Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'), ('Цельнометаллический Фургон', 'Цельнометаллический Фургон')], max_length=64, verbose_name='Кузов')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(choices=[('бежевый', 'бежевый'), ('белый', 'белый'), ('бронзовый', 'бронзовый'), ('вишнёвый', 'вишнёвый'), ('голубой', 'голубой'), ('жёлтый', 'жёлтый'), ('зелёный', 'зелёный'), ('золотистый', 'золотистый'), ('индивидуальная окраска', 'индивидуальная окраска'), ('коричневый', 'коричневый'), ('красный', 'красный'), ('оранжевый', 'оранжевый'), ('пурпурный', 'пурпурный'), ('серебристый', 'серебристый'), ('серый', 'серый'), ('синий', 'синий'), ('фиолетовый', 'фиолетовый'), ('чёрный', 'чёрный')], max_length=64, verbose_name='Цвет')),
                ('description', models.CharField(blank=True, max_length=4500, verbose_name='Описание')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Описание')),
                ('photo', models.CharField(blank=True, max_length=512, verbose_name='Ссылка на фото')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='services.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='services.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'ads_ad',
            },
        ),
    ]
