# Generated by Django 4.1.4 on 2024-08-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='accounts.client'),
        ),
    ]
