# Generated by Django 4.1.4 on 2023-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.CharField(blank=True, max_length=5120, verbose_name='Ссылка на фото'),
        ),
    ]
