# Generated by Django 4.1.4 on 2024-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_configuration_codes_ad_complectation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='configuration_codes',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Коды опций комплектации'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='complectation_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Код комплектации'),
        ),
    ]
