# Generated by Django 4.1.4 on 2023-12-06 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_description_alter_ad_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
