# Generated by Django 4.1.4 on 2024-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_salon_client'),
        ('ads', '0005_ad_configuration_codes_alter_ad_complectation_code'),
    ]

    operations = [
    ]
