# Generated by Django 4.1.4 on 2023-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_datetime_created_ad_datetime_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN'),
        ),
    ]
