# Generated by Django 4.1.4 on 2023-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_availability_ad_color_code_ad_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='power',
            field=models.IntegerField(blank=True, verbose_name='Мощность'),
        ),
    ]
