# Generated by Django 4.1.4 on 2023-12-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_modification_body_type'),
        ('ads', '0009_alter_ad_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='services.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='services.model', verbose_name='Модель'),
        ),
    ]
