# Generated by Django 4.1.4 on 2023-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_mark_alter_ad_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='run',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Пробег'),
        ),
    ]
