# Generated by Django 4.1.4 on 2024-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ad_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя'),
        ),
    ]
