# Generated by Django 4.1.4 on 2024-01-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_ad_engine_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='id_configuration_autoru',
        ),
    ]
