# Generated by Django 4.1.4 on 2024-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_remove_ad_currency_remove_ad_id_configuration_autoru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='configuration',
            new_name='complectation',
        ),
        migrations.AddField(
            model_name='ad',
            name='modification',
            field=models.CharField(blank=True, max_length=128, verbose_name='Модификация'),
        ),
    ]
